### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/probfit#102]
Seems it's time to get a new release out, as there have been very many commits since the last one.
Guess it should be 1.2.0 at this stage?

**Comment by HDembinski** [comment]
Feel free to take over making these decisions, I have to free time and probfit is something I would happily like to give someone else.

**Comment by henryiii** [comment]
Once we get the two PRs in, I think it's time to call a release (maybe @eduardo-rodrigues you'd like to fill out the CHANGELOG?). I'm expecting 1.2 is likely to be the last release, unless we have contributors or volunteers.

**Comment by eduardo-rodrigues** [comment]
> Once we get the two PRs in, I think it's time to call a release (maybe @eduardo-rodrigues you'd like to fill out the CHANGELOG?). I'm expecting 1.2 is likely to be the last release, unless we have contributors or volunteers.

Yes, happy to do that.
