### ISSUE TITLE
Add PyPI scikit-hep account as maintainer or owner

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/probfit#106]
@HDembinski, @piti118, @cdeil or @alexpearce, please add scikit-hep as a maintainer or owner for this package on PyPI. All Scikit-HEP packages should have scikit-hep listed. Thanks!

Comment taken from https://github.com/scikit-hep/probfit/pull/105#issuecomment-786787620.

**Comment by HDembinski** [comment]
I have invited scikit-hep two days ago, it says invitation pending.

**Comment by eduardo-rodrigues** [comment]
Done now, see my reply at https://github.com/scikit-hep/probfit/pull/105#issuecomment-787893873. Thank youo @HDembinski.
