### ISSUE TITLE
Port it to long double instead of double

### ISSUE THREAD

**Issue by piti118** [scikit-hep/probfit#13]
Unbinned likelihood calculation can benefit for very high precision sum. This will have to be done in conjunction with iminuit

**Comment by eduardo-rodrigues** [comment]
@HDembinski, shall this issue be simply closed at this stage? Seems fair, especially that this package is presently in maintenance mode.

**Comment by HDembinski** [comment]
Yes. I think probfit has to be rewritten without Cython and a fresh new interface (or we just use zfit ;)).
