### ISSUE TITLE
Performance check

### ISSUE THREAD

**Issue by piti118** [scikit-hep/probfit#34]
I tried the new version with my old analysis code and it seems to be much slower than before. Need to check what happen.

**Comment by eduardo-rodrigues** [comment]
@HDembinski , shall this issue be simply closed at this stage? Seems fair, especially that this package is presently in maintenance mode.

**Comment by eduardo-rodrigues** [comment]
Closing this issue since the package is in maintenance mode and clearly nobody is working on performance, at which point one would anyway move away from Cython.
