### ISSUE TITLE
Warnings in docs build

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/probfit#45]
I tried to clean up the docs a bit in #44, but I couldn't figure out how to fix these warnings (and one error) when building the docs:

```
$ cd doc
$ make clean
$ make html
...
docstring of probfit.costfunc.UnbinnedLH:10: WARNING: Explicit markup ends without a blank line; unexpected unindent.
docstring of probfit.costfunc.UnbinnedLH:42: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of probfit.costfunc.UnbinnedLH.draw:39: ERROR: Unexpected indentation.
docstring of probfit.costfunc.SimultaneousFit:1: WARNING: Inline emphasis start-string without end-string.
docstring of probfit.costfunc.SimultaneousFit:3: WARNING: Inline emphasis start-string without end-string.
docstring of probfit.functor.AddPdf:1: WARNING: Inline emphasis start-string without end-string.
docstring of probfit.functor.AddPdfNorm:1: WARNING: Inline emphasis start-string without end-string.
/Users/deil/code/probfit/doc/api.rst:203: WARNING: error while formatting arguments for probfit.pdf.linear: <method-wrapper '__init__' of probfit.pdf._Linear object at 0x10df213f8> is not a Python function
/Users/deil/code/probfit/doc/index.rst:1: WARNING: Inline emphasis start-string without end-string.
/Users/deil/code/probfit/doc/index.rst:1: WARNING: Inline emphasis start-string without end-string.
/Users/deil/code/probfit/doc/index.rst:1: WARNING: Inline emphasis start-string without end-string.
```

**Comment by alexpearce** [comment]
I see one warning:

```
probfit/doc/api.rst:206: WARNING: error while formatting arguments for probfit.pdf.linear: 'probfit.pdf._Linear' object has no attribute '__bases__'
```

The `_Linear` class is [defined in a Cython module](https://github.com/iminuit/probfit/blob/master/probfit/pdf.pyx#L277-L301). I think it's due to the same problem @cdeil saw:

```
probfit/doc/api.rst:203: WARNING: error while formatting arguments for probfit.pdf.linear: <method-wrapper '__init__' of probfit.pdf._Linear object at 0x10df213f8> is not a Python function
```

This is probably the thing addressed in the constructor of that class:

```python
    def __init__(self):
        #unfortunately cython doesn't support docstring for builtin class
        #http://docs.cython.org/src/userguide/special_methods.html
        ....
```

The error goes away if I mark `linear` as `autoclass`, but then it's not documented 😄 

I'm tempted to ignore it; the docs are built and look OK.

**Comment by cdeil** [comment]
@alexpearce - Thanks for looking into this issue.

It's completely harmless, yes, the docs output is fine.

The advantage of finding a way to fix or suppress the warning would be that with a "clean" Sphinx build, we can add the `-w` option on travis-ci to raise Warnings as errors, and that would make sure that for any future pull requests Sphinx formatting issues would immediately be flagged on travis-ci.

So I think there is some real benefit if we can find a way to suppress or ignore that warning.
That said, I don't know much about Cython/Sphinx and don't know how to fix this one.

So yes, for me just closing the issue would be OK, or keep it open and change milestone to "wishlist".

**Comment by eduardo-rodrigues** [comment]
I believe we can close this issue at this point.
