### ISSUE TITLE
Multi-dimensional histogram PDF?

### ISSUE THREAD

**Issue by clempiric** [scikit-hep/probfit#58]
Hello,

First, I want to say that I am excited to find this project. I have worked with Roofit, yet I have always wanted a package in Python. I think Probfit is a great start.

An enhanced feature that I would appreciate is a multi-dimensional histogram PDF. It is used extensively in my project, yet I do not see an easy way to implement it in Cython.

**Comment by cdeil** [comment]
@clempiric - Hi!

`probfit` development isn't very active, so don't expect anyone else to pick up this suggestion and implement it.
That said, if you make a pull request we'll put it in, and we might also be able to help with Cython issues if you have specific questions.

**Comment by alexpearce** [comment]
As far as I can tell, there hasn't been much work on multi-dimensional PDFs of any form in probfit. I imagine this being the next major development. @piti118 - any thoughts or ideas on this? Do you think probfit will need an overhaul for this, or perhaps work has already started in some parts of the codebase?

**Comment by eduardo-rodrigues** [comment]
This will not be done since the package is now effectively superseded and almost unmaintained. Closing.
