### ISSUE TITLE
Release probfit 1.1

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/probfit#65]
The last probfit release is `1.0.5` from 2013:
https://pypi.python.org/pypi/probfit/1.0.5

I'd like to release a new version `1.1` now that `probfit` works with Python 3.

@piti118 - Do you want to make a release? Or can you please give me access on PyPI for probfit?

**Comment by cdeil** [comment]
@piti118 - Could you please give @alexpearce and me access on PyPI? 
https://pypi.python.org/pypi/probfit/

@alexpearce is fixing up some issues now and would be willing to make a release soon.

**Comment by piti118** [comment]
added @cedil as owner.

**Comment by cdeil** [comment]
@piti118 - Thanks

@alexpearce - I've added you as "maintainer". I think this means you can make and upload the 1.1 release (but not add others or delete the package).

**Comment by alexpearce** [comment]
Thanks @cdeil! I'll work on the milestone on come back to this issue once we're ready.

**Comment by fjankowsk** [comment]
Hello guys,

Would it be possible to tag version 1.1 now and update it on pypi? pypi currently still has probfit version 1.0.5, which does not have the code adjustments for Python 3 and consequently fails there (the current master works fine though). If version 1.1 requires more work, why not tag 1.0.6 for the meantime? Python 3 support alone is worth a version bump in my opinion.

Cheers!

**Comment by eduardo-rodrigues** [comment]
Hi folks, a version 1.1.0 working with Python 3 is now a reality, see https://github.com/scikit-hep/probfit/pull/95. The release on PyPI will come out shortly.

**Comment by eduardo-rodrigues** [comment]
The tag is done - https://github.com/scikit-hep/probfit/releases/tag/1.1.0.

Can one of you maintainers on PyPI (@cdeil, @piti118, @alexpearce, @HDembinski) upload to PyPI asap and close this? Would be great, thanks a lot.

**Comment by HDembinski** [comment]
@cdeil I can see probfit listed as "my projects" when I log into PyPI, but the "Management" button is grayed out. I am not sure if I can upload this version.

**Comment by cdeil** [comment]
@HDembinski - you were maintainer and already had permission to upload releases:

```
There are two possible roles for collaborators:

Maintainer
Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project.
Owner
Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project.
```

I changed you to owner just now, so you can add other collaborators as useful.

**Comment by HDembinski** [comment]
Thanks! But this means, I can upload the package. ok.

**Comment by HDembinski** [comment]
It is uploaded. Installation via pip seems to work.

**Comment by eduardo-rodrigues** [comment]
Thanks @HDembinski.
