### ISSUE TITLE
Exception when `pip install probfit`

### ISSUE THREAD

**Issue by dneise** [scikit-hep/probfit#85]
```
16:15 $ pip install probfit
Collecting probfit
  Using cached https://files.pythonhosted.org/packages/80/2c/0abaeede057064b1eacbdb839f33b88693c3e0f3d78a405e1e0d5a8b446b/probfit-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2oz5tpmd/probfit/setup.py", line 43, in <module>
        execfile('probfit/info.py')
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2oz5tpmd/probfit/
```

using anaconda python 3.6.6

**Comment by raymondEhlers** [comment]
The current package on PyPI doesn't support python 3. See #65 - you could add another comment to encourage them to add a new release.

In the meantime, it should work if you install it from master `pip install git+https://github.com/iminuit/probfit.git#egg=probfit`

**Comment by eduardo-rodrigues** [comment]
Hi @dneise and @raymondEhlers, a release working with Python 3 will hopefully be out soon. As you can see from the activity, we're trying to iron out a few things.

**Comment by raymondEhlers** [comment]
Hi @eduardo-rodrigues, thanks for the efforts - they are much appreciated!

**Comment by eduardo-rodrigues** [comment]
Hi folks, pobfit's build is finally passing again! Can you give it a try for yourselves and close this, if happy? Thanks a lot.

**Comment by eduardo-rodrigues** [comment]
probfit 1.1.0 is available on PyPI. Am closing this PR as I believe it's all sorted out.

Feel free to reopen if you have any trouble. Otherwise … enjoy!

**Comment by raymondEhlers** [comment]
It took me a few days to make time to try it out, but just wanted to follow up to say that it seems to be working nicely. Thanks!
