### ISSUE TITLE
Tutorial does not work

### ISSUE THREAD

**Issue by Norhk** [scikit-hep/probfit#86]
Pulled master and executed with python3 yields:

    import probfit

    ModuleNotFoundError: No module named 'probfit.costfunc'

**Comment by eduardo-rodrigues** [comment]
Hello, can you try again with the head? We are trying to iron out a few things in order to make a new release - last one was a long time ago. Thanks a lot.

**Comment by eduardo-rodrigues** [comment]
This is fixed in the head. Note that a release will come shortly. Do give it at try … Thanks!
