### ISSUE TITLE
Sync releases info on PyPI with tags on GitHub

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/probfit#88]
I see many 1.0.x releases on PyPI (https://pypi.org/project/probfit/#history) but only one very old release on GitHub, with version number v0.01.

It is important to have these things in sync and also make a newer release taking on board all recent commits.

**Comment by eduardo-rodrigues** [comment]
Explicit cc to @HDembinski, @cdeil and @alexpearce.

**Comment by cdeil** [comment]
Well, ideally there would be one person that's willing to spend a day or two on this project to get it in shape again:

- Fix CI, make sure it works on Python 2 an 3
- Fix Readthedocs
- Tag a stable version 1.1 or 2.0 and release on PyPI

Anyone willing to do this?
(for me no)

**Comment by eduardo-rodrigues** [comment]
My officemate @henryiii is helping a lot with the technical issues, and has made great progress in understanding compilation issues, see his comment at https://github.com/scikit-hep/probfit/pull/81. But he has a lot of things going on ... It would be ideal to get a user to jump in ... Since you are one of the iminuit people, would you be willing to email the scikit-hep-forum list to see if anyone is interested? We have the list for these matters too ;-).

**Comment by eduardo-rodrigues** [comment]
I've just done the above, modulo the upload to PyPI, which I do not have right for. Closing this.
