### ISSUE TITLE
Automatic upload of releases to PyPI via Travis

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/probfit#97]
This would be really handy. It allows any one of us admins to tag a release and get it to PyPI with no extra work.

Can one of you maintainers do this? We have it for most of the other packages.

Thanks a lot.

**Comment by HDembinski** [comment]
Sounds very good, I would like to have this for iminuit and probfit. Which package works best as an example on how to achieve this?

**Comment by eduardo-rodrigues** [comment]
Both scikit-hep and uproot and others have the necessary lines in the travis YAML file. I cannot remember how I got the key for Travis, off the top of my head, though :S.
